#Data types and structure assignment

  1. What are data structures, and why are they important
  --data structures are the formats which is used to store and access data according to needs of user. they are important because they help in data manipulation and sorting


  2. Explain the difference between mutable and immutable data types with examples
  --mutable data type include list where element can be changed, altered, deleted without assigning a new variable but muatable data type include string or tuple which means it cant be alterted and trying to do so gives an error


  3. What are the main differences between lists and tuples in Python
  --list are mutable type of data structures where elements can be altered. it is called out using []
  tuple on other hand is immutable data structure and elements in tuple cant be chnaged . it is called out using ()


  4. Describe how dictionaries store data
  --dictionary is type of data structure which stores data as key-value pair for example {"key" : "value"}


  5. Why might you use a set instead of a list in Python
  --set is the unordered collection of unique data althoug mutable sets contain unique elements to avoid repetition of enteries


  6. What is a string in Python, and how is it different from a list
  --string is an immutable data type in python which supports indexing though but list is a data structure which contains ordered data but is mutable in nature


  7. How do tuples ensure data integrity in Python
  --tuples ensure data intergrity by being immutable which means once atuple is made and its values are assigned these cant be changed thus making sure that things like employee id cant be misused


  8. What is a hash table, and how does it relate to dictionaries in Python
  --hash table is something which assignes multiple values to keys it is the same thing as dictionary in python because it also stores data in key and value pair where key also act as an index to call out an entry


  9. Can lists contain different data types in Python
  --yes list can contain heterogenous data in itself meaning a list can have interger, string, float and boolean as an element


  10. Explain why strings are immutable in Python
  --strings are immutable to ensure data security, simplicity and efficiency in python code


  11. What advantages do dictionaries offer over lists for certain tasks
  --dictionaries offer data storage as key value pair in which single key can contain multiple values example key name can contain name of multiple students but in list everyname had to definded individually and data retrieving is also easier by use of dictionaries


  12. Describe a scenario where using a tuple would be preferable over a list
  --a scenario where using tuple will be preferred over list is when the data stored is something like aadhar card number, bank account number which should be immune to editing


  13. How do sets handle duplicate values in Python
  --sets are designed to store unique data if any duplicate is added sets discard that thus making it unordered


  14. How does the “in” keyword work differently for lists and dictionaries
  --for list in checks if the value is present or not but for dictionaries it checks if that key is present or not
  
  
  15. Can you modify the elements of a tuple? Explain why or why not
  --no u cant because tuples are immutable data structure in python language


  16. What is a nested dictionary, and give an example of its use case
  --nested dictionary is the dictionary where value of a particular key is a dictionary and it can be used keeping employee records , address


  17. Describe the time complexity of accessing elements in a dictionary
  --


  18. In what situations are lists preferred over dictionaries
  --list can be preferred over dictionaries when data to be stored is to be edited frequently and ordered properly like tasks given


  19.  Why are dictionaries considered unordered, and how does that affect data retrieval
  --dictionaries are unordered because the concept of numbering elements i.e. indexing does not work in dictionaries thus data retrieval requires user to enter a whole key rather than single number


  20. Explain the difference between a list and a dictionary in terms of data retrieval
  --data retieval in lists work through indexing which means a number is assigned to each element in a list but in dictionary this indexing does not work thus data retieval here works by calling out key

In [ ]:
#1. Write a code to create a string with your name and print it
s = "Shourya"
print(s)

Shourya

In [ ]:
#2. Write a code to find the length of the string "Hello World"
s1 = "Hello World"
len(s1)

11

In [ ]:
#3. Write a code to slice the first 3 characters from the string "Python Programming
s2 = "Python Programming"
s2[0:3]

'Pyt'

In [ ]:
#4. Write a code to convert the string "hello" to uppercase
s3 = "hello"
s3.upper()

'HELLO'

In [ ]:
#5. Write a code to replace the word "apple" with "orange" in the string "I like apple
s4 = "I like apple"
s4.replace("apple", "orange")

'I like orange'

In [ ]:
#6. Write a code to create a list with numbers 1 to 5 and print it
lst1 = list(range(1,6))
print(lst1)

[1, 2, 3, 4, 5]

In [ ]:
#7. Write a code to append the number 10 to the list [1, 2, 3, 4]
lst2 = [1,2,3,4]
lst2.append(10)
print(lst2)

[1, 2, 3, 4, 10]

In [ ]:
#8.  Write a code to remove the number 3 from the list [1, 2, 3, 4, 5]
lst3 = [1,2,3,4,5]
lst3.remove(3)
print(lst3)

[1, 2, 4, 5]

In [ ]:
#9. Write a code to access the second element in the list ['a', 'b', 'c', 'd']
lst4 = ["a","b","c","d"]
lst4[1]

'b'

In [ ]:
#10. Write a code to reverse the list [10, 20, 30, 40, 50].
lst5 = [10,20,30,40,50]
lst5.reverse()
lst5

[50, 40, 30, 20, 10]

In [ ]:
#11. Write a code to create a tuple with the elements 100, 200, 300 and print it
t = (100,200,300)
print(t)

(100, 200, 300)

In [ ]:
#12. Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow')
t2 = ('red', 'green', 'blue', 'yellow')
t2[-2:]

('blue', 'yellow')

In [ ]:
#13. Write a code to find the minimum number in the tuple (10, 20, 5, 15)
t3 = (10, 20, 5, 15)
min(t3)

5

In [ ]:
#14. Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit')
t4 = ('dog', 'cat', 'rabbit')
t4.index("cat")

1

In [ ]:
#15. Write a code to create a tuple containing three different fruits and check if "kiwi" is in it
t5 = ("apple", "mango", "pineapple")
"kiwi" in t5

False

In [ ]:
#other case of 15
t6 = ("apple", "mango","kiwi")
"kiwi" in t6

True

In [ ]:
#16. Write a code to create a set with the elements 'a', 'b', 'c' and print it
st = {'a', 'b', 'c'}
print(st)

{'c', 'b', 'a'}

In [ ]:
#17. Write a code to clear all elements from the set {1, 2, 3, 4, 5}.
st1 = {1, 2, 3, 4, 5}
st1.clear()
print(st1)

set()

In [ ]:
#18. Write a code to remove the element 4 from the set {1, 2, 3, 4}
st2 = {1, 2, 3, 4}
st2.remove(4)
st2

{1, 2, 3}

In [ ]:
#19. Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}
st3 = {1, 2, 3}
st4= {3, 4, 5}
st3 | st4

{1, 2, 3, 4, 5}

In [ ]:
#20.  Write a code to find the intersection of two set {1, 2, 3} and {2, 3, 4}
st5 = {1, 2, 3}
st6 = {2, 3, 4}
st5.intersection(st6)

{2, 3}

In [1]:
#21. Write a code to create a dictionary with the keys "name", "age", and "city", and print it
dict1 = {"name" : "Shourya", "age" : "21", "city" : "Chandigarh"}
dict1

{'name': 'Shourya', 'age': '21', 'city': 'Chandigarh'}

In [6]:
#22. Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}
dict2 = {'name': 'John', 'age': 25}
dict2.update({"country" : "USA"})
dict2

{'name': 'John', 'age': 25, 'country': 'USA'}

In [7]:
#23. Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30}
dict3 = {'name': 'Alice', 'age': 30}
dict3["name"]

'Alice'

In [10]:
#24. Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}
dict4 = {'name': 'Bob', 'age': 22, 'city': 'New York'}
dict4.pop("age")
dict4

{'name': 'Bob', 'city': 'New York'}

In [11]:
#25. Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}
dict5 = {'name': 'Alice', 'city': 'Paris'}
'city' in dict5

True

In [12]:
#26. Write a code to create a list, a tuple, and a dictionary, and print them all
lst = [1,2,3,4,5,6]
tp = (1,2,3,4,5,6)
dic = {'a' : 1 , 'b' : 2, 'c' : 3, 'd' : 4}
print(lst)
print(tp)
print(dic)

[1, 2, 3, 4, 5, 6]
(1, 2, 3, 4, 5, 6)
{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [15]:
#27. Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the result.(replaced)
lst6 = [95, 54, 42, 37, 88]
lst6.sort()
print(lst6)

[37, 42, 54, 88, 95]

In [16]:
#28. Write a code to create a list with strings and print the element at the third index
lst7 = ['a', 'b', 'c', 'd', 'e', 'f']
lst7[3]

'd'

In [19]:
#29. Write a code to combine two dictionaries into one and print the result
dict6 = {'a' : 1 , 'b' : 2}
dict7 = {'c' : 3 , 'd' : 4}
dict6.update(dict7)
print(dict6)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [24]:
#30. Write a code to convert a list of strings into a set
lst8 = ['a', 'b', 'c', 'd', 'e', 'f']
st7 = set(lst8)
print(st7)

{'c', 'b', 'e', 'd', 'a', 'f'}